image: node:10.7.0-alpine

stages:
- build
- deploy

build:
  stage: build
  script:
  - npm ci
  - source scripts/set_release_version_env.sh
  - npm run build
  artifacts:
    expire_in: 1 week
    paths:
    - dist

deploy:
  stage: deploy
  script:
  - npm install -g firebase-tools
  - firebase use --token $FIREBASE_TOKEN default
  - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --only hosting --non-interactive --token $FIREBASE_TOKEN
  - npm install -g @sentry/cli --unsafe-perm
  - sh scripts/sentry.sh
  environment:
    name: stage
    url: https://drub-1b838.firebaseapp.com/
  only:
  - master
